-- MOTO MASTER - DESIGN TABLES (run once in Neon SQL Editor)
-- Replaces: designs, design_winding_data, calculations, reports
-- Does NOT touch: users, subscriptions, payments

BEGIN;

-- Stop if old designs table has data (nothing is changed)
DO $$
DECLARE n BIGINT := 0;
BEGIN
    IF to_regclass('public.designs') IS NOT NULL THEN
        EXECUTE 'SELECT COUNT(*) FROM designs' INTO n;
    END IF;
    IF n > 0 THEN
        RAISE EXCEPTION 'designs table has % row(s). Migration stopped.', n;
    END IF;
END $$;

DROP VIEW  IF EXISTS design_full;
DROP TABLE IF EXISTS reports             CASCADE;
DROP TABLE IF EXISTS calculations        CASCADE;
DROP TABLE IF EXISTS design_winding_data CASCADE;
DROP TABLE IF EXISTS designs             CASCADE;

-- ---------- helper functions ----------
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION touch_parent_design()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE designs SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.design_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------- designs (step 1 phase + step 2 components) ----------
CREATE TABLE designs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    design_no   VARCHAR(100),
    design_name VARCHAR(150) NOT NULL,
    design_date DATE NOT NULL DEFAULT CURRENT_DATE,
    phase VARCHAR(10) NOT NULL
        CHECK (phase IN ('1_phase', '2_phase', '3_phase')),
    wire_type VARCHAR(30)
        CHECK (wire_type IN ('copper_pvc_pp', 'copper_enamel', 'aluminium_pvc_pp', 'aluminium_enamel')),
    mechanical_component VARCHAR(20)
        CHECK (mechanical_component IN ('bush', 'ball_bearing')),
    status VARCHAR(20) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'completed')),
    current_step SMALLINT NOT NULL DEFAULT 1
        CHECK (current_step BETWEEN 1 AND 4),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_designs_user_design_no ON designs(user_id, design_no) WHERE design_no IS NOT NULL;
CREATE INDEX idx_designs_user_updated ON designs(user_id, updated_at DESC);

-- ---------- form 1: main data ----------
CREATE TABLE design_main_data (
    design_id BIGINT PRIMARY KEY REFERENCES designs(id) ON DELETE CASCADE,
    connection VARCHAR(30),
    voltage    NUMERIC(10,2) CHECK (voltage > 0),
    power      NUMERIC(12,2) CHECK (power > 0),
    hp         NUMERIC(8,3)  CHECK (hp > 0),
    frequency  SMALLINT      CHECK (frequency IN (50, 60)),
    rpm        INTEGER       CHECK (rpm > 0),
    pole       SMALLINT      CHECK (pole IN (2, 4, 6, 8, 10, 12)),
    uph        NUMERIC(10,2) CHECK (uph > 0),
    capacitor  NUMERIC(10,2) CHECK (capacitor >= 0),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------- form 2: stamping ----------
CREATE TABLE design_stamping_data (
    design_id BIGINT PRIMARY KEY REFERENCES designs(id) ON DELETE CASCADE,
    material          VARCHAR(20) CHECK (material IN ('copper', 'aluminium')),
    stamping_material VARCHAR(20) CHECK (stamping_material IN ('CRC', 'CRNO', 'M-47')),
    n   INTEGER CHECK (n > 0),
    y   NUMERIC(10,3),
    w   NUMERIC(10,3),
    w2  NUMERIC(10,3),
    a1  NUMERIC(12,3),
    shape VARCHAR(10) CHECK (shape IN ('Round', 'Trp')),
    a   NUMERIC(10,3),
    b   NUMERIC(10,3),
    c   NUMERIC(10,3),
    d   NUMERIC(10,3),
    e   NUMERIC(10,3),
    dw  NUMERIC(10,3),
    d0  NUMERIC(10,3) CHECK (d0 > 0),
    dia NUMERIC(10,3) CHECK (dia > 0),
    lf_y NUMERIC(8,3),
    lf_t NUMERIC(8,3),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT stamping_diameter_check CHECK (d0 IS NULL OR dia IS NULL OR d0 > dia)
);

-- ---------- form 3: rotor ----------
CREATE TABLE design_rotor_data (
    design_id BIGINT PRIMARY KEY REFERENCES designs(id) ON DELETE CASCADE,
    m      INTEGER CHECK (m > 0),
    rng_wt NUMERIC(10,3),
    rng_ht NUMERIC(10,3),
    x      NUMERIC(10,3),
    v      NUMERIC(10,3),
    v2     NUMERIC(10,3),
    a2     NUMERIC(12,3),
    ra NUMERIC(10,3),
    rb NUMERIC(10,3),
    rc NUMERIC(10,3),
    rd NUMERIC(10,3),
    re NUMERIC(10,3),
    rw NUMERIC(10,3),
    shaft_diameter NUMERIC(10,3) CHECK (shaft_diameter > 0),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------- form 4: winding (user inputs) ----------
CREATE TABLE design_winding_data (
    design_id BIGINT PRIMARY KEY REFERENCES designs(id) ON DELETE CASCADE,
    current_density    NUMERIC(8,3)  CHECK (current_density > 0),
    efficiency         NUMERIC(6,2)  CHECK (efficiency > 0 AND efficiency <= 100),
    insulation_dia     NUMERIC(8,4)  CHECK (insulation_dia > 0),
    actual_use_dia     NUMERIC(8,4)  CHECK (actual_use_dia > 0),
    final_turns        INTEGER       CHECK (final_turns > 0),
    insulation_dia_aux NUMERIC(8,4)  CHECK (insulation_dia_aux > 0),   -- 1/2-phase only
    actual_use_dia_aux NUMERIC(8,4)  CHECK (actual_use_dia_aux > 0),   -- 1/2-phase only
    final_turns_aux    INTEGER       CHECK (final_turns_aux > 0),      -- 1/2-phase only
    final_stack_length NUMERIC(10,3) CHECK (final_stack_length > 0),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3-phase designs cannot have auxiliary winding values
CREATE OR REPLACE FUNCTION check_winding_matches_phase()
RETURNS TRIGGER AS $$
BEGIN
    IF (SELECT phase FROM designs WHERE id = NEW.design_id) = '3_phase'
       AND (NEW.insulation_dia_aux IS NOT NULL
            OR NEW.actual_use_dia_aux IS NOT NULL
            OR NEW.final_turns_aux IS NOT NULL) THEN
        RAISE EXCEPTION 'Auxiliary winding values are only allowed for 1_phase / 2_phase designs';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------- calculated results (history) ----------
CREATE TABLE calculations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    design_id BIGINT NOT NULL REFERENCES designs(id) ON DELETE CASCADE,
    i_ph  NUMERIC(12,4),
    i_aux NUMERIC(12,4),
    recommended_dia          NUMERIC(10,4),
    recommended_dia_aux      NUMERIC(10,4),
    recommended_turns        NUMERIC(12,3),
    recommended_turns_aux    NUMERIC(12,3),
    recommended_stack_length NUMERIC(12,3),
    slip             NUMERIC(10,4),
    temp             NUMERIC(10,4),
    statorwt         NUMERIC(12,4),
    rotorwt          NUMERIC(12,4),
    cu_length        NUMERIC(14,4),
    air_gap          NUMERIC(10,4),
    final_efficiency NUMERIC(8,4),
    angle            NUMERIC(8,4),
    torque           NUMERIC(12,4),
    inputs_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_calculations_design_created ON calculations(design_id, created_at DESC);

-- ---------- reports ----------
CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    design_id      BIGINT NOT NULL REFERENCES designs(id)      ON DELETE CASCADE,
    calculation_id BIGINT NOT NULL REFERENCES calculations(id) ON DELETE CASCADE,
    report_name VARCHAR(200) NOT NULL,
    file_url TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_reports_design_id ON reports(design_id);
CREATE INDEX idx_reports_calculation_id ON reports(calculation_id);

-- ---------- triggers ----------
CREATE TRIGGER update_designs_updated_at       BEFORE UPDATE ON designs              FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_main_data_updated_at     BEFORE UPDATE ON design_main_data     FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_stamping_data_updated_at BEFORE UPDATE ON design_stamping_data FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_rotor_data_updated_at    BEFORE UPDATE ON design_rotor_data    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_winding_data_updated_at  BEFORE UPDATE ON design_winding_data  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER check_winding_phase BEFORE INSERT OR UPDATE ON design_winding_data FOR EACH ROW EXECUTE FUNCTION check_winding_matches_phase();

CREATE TRIGGER touch_design_from_main        AFTER INSERT OR UPDATE ON design_main_data     FOR EACH ROW EXECUTE FUNCTION touch_parent_design();
CREATE TRIGGER touch_design_from_stamping    AFTER INSERT OR UPDATE ON design_stamping_data FOR EACH ROW EXECUTE FUNCTION touch_parent_design();
CREATE TRIGGER touch_design_from_rotor       AFTER INSERT OR UPDATE ON design_rotor_data    FOR EACH ROW EXECUTE FUNCTION touch_parent_design();
CREATE TRIGGER touch_design_from_winding     AFTER INSERT OR UPDATE ON design_winding_data  FOR EACH ROW EXECUTE FUNCTION touch_parent_design();
CREATE TRIGGER touch_design_from_calculation AFTER INSERT ON calculations                   FOR EACH ROW EXECUTE FUNCTION touch_parent_design();

COMMIT;
