-- ============================================================
-- MOTO MASTER - COMPLETE DATABASE SCHEMA  (v2)
-- PostgreSQL / Neon
--
-- Design tables are built to match the design forms exactly:
--
--   Step 1  Phase                 -> designs.phase
--   Step 2  Basic components      -> designs.wire_type, designs.mechanical_component
--   Form 1  Main Data             -> design_main_data
--   Form 2  Stamping Parameters   -> design_stamping_data
--   Form 3  Rotor Parameters      -> design_rotor_data
--   Form 4  Winding Parameters    -> design_winding_data   (values the user types)
--   Result  Calculated values     -> calculations           (values the app works out)
--   Report  Generated report      -> reports
--
-- Column names are the form field ids in lower case
-- (e.g. form id "A1" -> column a1, "shaft_diameter" -> shaft_diameter),
-- so saving a form is a direct field -> column copy.
--
-- Every form column is NULL-able: a design is saved as a DRAFT
-- step by step, and a field is only filled once the user reaches it.
-- ============================================================


-- ============================================================
-- 1. USERS
-- ============================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(100) NOT NULL,

    username VARCHAR(50) NOT NULL UNIQUE,

    email VARCHAR(150) NOT NULL UNIQUE,

    password_hash TEXT NOT NULL,

    -- Public registration always creates role = user.
    -- Admin can be manually changed in the database.
    role VARCHAR(20) NOT NULL DEFAULT 'user',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT users_role_check
        CHECK (role IN ('user', 'admin'))
);


-- ============================================================
-- 2. SUBSCRIPTIONS
-- ============================================================

CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    plan VARCHAR(30) NOT NULL,

    amount NUMERIC(10,2) NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'pending',

    start_date TIMESTAMP,

    end_date TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT subscriptions_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT subscriptions_plan_check
        CHECK (plan IN ('weekly', 'monthly', 'yearly')),

    CONSTRAINT subscriptions_status_check
        CHECK (status IN (
            'pending',
            'active',
            'expired',
            'cancelled'
        )),

    CONSTRAINT subscriptions_amount_check
        CHECK (amount >= 0)
);


-- ============================================================
-- 3. PAYMENTS
-- ============================================================

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    subscription_id BIGINT,

    gateway_order_id VARCHAR(150),

    gateway_payment_id VARCHAR(150),

    amount NUMERIC(10,2) NOT NULL,

    currency VARCHAR(10) NOT NULL DEFAULT 'INR',

    status VARCHAR(20) NOT NULL DEFAULT 'created',

    paid_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT payments_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT payments_subscription_fk
        FOREIGN KEY (subscription_id)
        REFERENCES subscriptions(id)
        ON DELETE SET NULL,

    CONSTRAINT payments_status_check
        CHECK (status IN (
            'created',
            'success',
            'failed',
            'refunded'
        )),

    CONSTRAINT payments_amount_check
        CHECK (amount >= 0)
);


-- ============================================================
-- SHARED: automatic updated_at
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- When any form of a design is saved, bump designs.updated_at
-- so "Recent designs" on the dashboard shows the right order.
CREATE OR REPLACE FUNCTION touch_parent_design()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE designs
    SET updated_at = CURRENT_TIMESTAMP
    WHERE id = NEW.design_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- 4. DESIGNS
-- One row per design. Holds the design identity plus
-- Step 1 (phase) and Step 2 (wire type, mechanical component).
-- ============================================================

CREATE TABLE designs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    -- Main Data header fields
    design_no   VARCHAR(100),
    design_name VARCHAR(150) NOT NULL,
    design_date DATE NOT NULL DEFAULT CURRENT_DATE,

    -- Step 1: Select Phase
    phase VARCHAR(10) NOT NULL,

    -- Step 2: Basic Components
    wire_type VARCHAR(30),
    mechanical_component VARCHAR(20),

    -- draft     = forms still being filled
    -- completed = winding calculated and report generated
    status VARCHAR(20) NOT NULL DEFAULT 'draft',

    -- Last form the user reached (1 = Main Data ... 4 = Winding)
    current_step SMALLINT NOT NULL DEFAULT 1,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT designs_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT designs_phase_check
        CHECK (phase IN ('1_phase', '2_phase', '3_phase')),

    CONSTRAINT designs_wire_type_check
        CHECK (wire_type IS NULL OR wire_type IN (
            'copper_pvc_pp',
            'copper_enamel',
            'aluminium_pvc_pp',
            'aluminium_enamel'
        )),

    CONSTRAINT designs_mechanical_check
        CHECK (mechanical_component IS NULL OR mechanical_component IN (
            'bush',
            'ball_bearing'
        )),

    CONSTRAINT designs_status_check
        CHECK (status IN ('draft', 'completed')),

    CONSTRAINT designs_step_check
        CHECK (current_step BETWEEN 1 AND 4)
);

-- A user cannot reuse the same design number.
CREATE UNIQUE INDEX uq_designs_user_design_no
ON designs(user_id, design_no)
WHERE design_no IS NOT NULL;

CREATE INDEX idx_designs_user_updated
ON designs(user_id, updated_at DESC);

CREATE INDEX idx_designs_phase
ON designs(phase);

CREATE TRIGGER update_designs_updated_at
BEFORE UPDATE ON designs
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- ============================================================
-- 5. FORM 1 - MAIN DATA
-- Form ids: connection, voltage, power, hp, frequency, rpm,
--           pole, uph, capacitor
-- (design_no / design_name / date live on designs)
-- ============================================================

CREATE TABLE design_main_data (
    design_id BIGINT PRIMARY KEY,

    connection VARCHAR(30),          -- 3-phase: Star / Delta / Series / Parallel; 1/2-phase: free text
    voltage    NUMERIC(10,2),        -- V
    power      NUMERIC(12,2),        -- W
    hp         NUMERIC(8,3),         -- HP
    frequency  SMALLINT,             -- Hz
    rpm        INTEGER,
    pole       SMALLINT,
    uph        NUMERIC(10,2),        -- phase voltage
    capacitor  NUMERIC(10,2),        -- 1 / 2-phase only (µF)

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT main_data_design_fk
        FOREIGN KEY (design_id)
        REFERENCES designs(id)
        ON DELETE CASCADE,

    CONSTRAINT main_data_frequency_check
        CHECK (frequency IS NULL OR frequency IN (50, 60)),

    CONSTRAINT main_data_pole_check
        CHECK (pole IS NULL OR pole IN (2, 4, 6, 8, 10, 12)),

    CONSTRAINT main_data_positive_check
        CHECK (
            (voltage   IS NULL OR voltage   > 0) AND
            (power     IS NULL OR power     > 0) AND
            (hp        IS NULL OR hp        > 0) AND
            (rpm       IS NULL OR rpm       > 0) AND
            (uph       IS NULL OR uph       > 0) AND
            (capacitor IS NULL OR capacitor >= 0)
        )
);


-- ============================================================
-- 6. FORM 2 - STAMPING PARAMETERS
-- Form ids: material, stamping_material, N, Y, W, W2, A1, shape,
--           a, b, c, d, e, dw, d0, dia   (+ lf_y, lf_t derived)
-- Dimensions in mm, areas in mm².
-- ============================================================

CREATE TABLE design_stamping_data (
    design_id BIGINT PRIMARY KEY,

    material          VARCHAR(20),   -- rotor bar material: copper / aluminium
    stamping_material VARCHAR(20),   -- CRC / CRNO / M-47

    n   INTEGER,                     -- N  : stator slots
    y   NUMERIC(10,3),               -- Y  : stator yoke depth
    w   NUMERIC(10,3),               -- W  : tooth width
    w2  NUMERIC(10,3),               -- W2 : tooth height
    a1  NUMERIC(12,3),               -- A1 : stator slot area

    shape VARCHAR(10),               -- Round / Trp

    a   NUMERIC(10,3),
    b   NUMERIC(10,3),
    c   NUMERIC(10,3),
    d   NUMERIC(10,3),
    e   NUMERIC(10,3),
    dw  NUMERIC(10,3),

    d0  NUMERIC(10,3),               -- stator outer diameter
    dia NUMERIC(10,3),               -- stator inner (bore) diameter

    -- Loss factors, set automatically from stamping_material
    lf_y NUMERIC(8,3),
    lf_t NUMERIC(8,3),

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT stamping_design_fk
        FOREIGN KEY (design_id)
        REFERENCES designs(id)
        ON DELETE CASCADE,

    CONSTRAINT stamping_material_check
        CHECK (material IS NULL OR material IN ('copper', 'aluminium')),

    CONSTRAINT stamping_steel_check
        CHECK (stamping_material IS NULL OR stamping_material IN ('CRC', 'CRNO', 'M-47')),

    CONSTRAINT stamping_shape_check
        CHECK (shape IS NULL OR shape IN ('Round', 'Trp')),

    CONSTRAINT stamping_positive_check
        CHECK (
            (n   IS NULL OR n   > 0) AND
            (d0  IS NULL OR d0  > 0) AND
            (dia IS NULL OR dia > 0)
        ),

    CONSTRAINT stamping_diameter_check
        CHECK (d0 IS NULL OR dia IS NULL OR d0 > dia)
);


-- ============================================================
-- 7. FORM 3 - ROTOR PARAMETERS
-- Form ids: M, rng_wt, rng_ht, X, V, V2, A2,
--           ra, rb, rc, rd, re, rw, shaft_diameter
-- ============================================================

CREATE TABLE design_rotor_data (
    design_id BIGINT PRIMARY KEY,

    m      INTEGER,                  -- M  : rotor slots / bars
    rng_wt NUMERIC(10,3),            -- end ring width
    rng_ht NUMERIC(10,3),            -- end ring height
    x      NUMERIC(10,3),            -- X  : rotor yoke depth
    v      NUMERIC(10,3),            -- V  : rotor tooth width
    v2     NUMERIC(10,3),            -- V2 : rotor tooth height
    a2     NUMERIC(12,3),            -- A2 : rotor slot area

    ra NUMERIC(10,3),
    rb NUMERIC(10,3),
    rc NUMERIC(10,3),
    rd NUMERIC(10,3),
    re NUMERIC(10,3),
    rw NUMERIC(10,3),

    shaft_diameter NUMERIC(10,3),

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT rotor_design_fk
        FOREIGN KEY (design_id)
        REFERENCES designs(id)
        ON DELETE CASCADE,

    CONSTRAINT rotor_positive_check
        CHECK (
            (m              IS NULL OR m              > 0) AND
            (shaft_diameter IS NULL OR shaft_diameter > 0)
        )
);


-- ============================================================
-- 8. FORM 4 - WINDING PARAMETERS (user inputs only)
-- Form ids: current_density, efficiency, insulation_dia,
--           actual_use_dia, final_turns, final_stack_length
-- 1 / 2-phase also: insulation_dia_aux, actual_use_dia_aux,
--                   final_turns_aux
-- Everything the app calculates goes to `calculations`.
-- ============================================================

CREATE TABLE design_winding_data (
    design_id BIGINT PRIMARY KEY,

    current_density    NUMERIC(8,3),     -- A/mm²
    efficiency         NUMERIC(6,2),     -- recommended efficiency, %

    -- Main (3-phase: the only) winding
    insulation_dia     NUMERIC(8,4),     -- mm
    actual_use_dia     NUMERIC(8,4),     -- mm
    final_turns        INTEGER,

    -- Auxiliary winding (1 / 2-phase only, NULL for 3-phase)
    insulation_dia_aux NUMERIC(8,4),
    actual_use_dia_aux NUMERIC(8,4),
    final_turns_aux    INTEGER,

    final_stack_length NUMERIC(10,3),    -- mm

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT winding_design_fk
        FOREIGN KEY (design_id)
        REFERENCES designs(id)
        ON DELETE CASCADE,

    CONSTRAINT winding_positive_check
        CHECK (
            (current_density    IS NULL OR current_density    > 0) AND
            (efficiency         IS NULL OR (efficiency > 0 AND efficiency <= 100)) AND
            (insulation_dia     IS NULL OR insulation_dia     > 0) AND
            (actual_use_dia     IS NULL OR actual_use_dia     > 0) AND
            (final_turns        IS NULL OR final_turns        > 0) AND
            (insulation_dia_aux IS NULL OR insulation_dia_aux > 0) AND
            (actual_use_dia_aux IS NULL OR actual_use_dia_aux > 0) AND
            (final_turns_aux    IS NULL OR final_turns_aux    > 0) AND
            (final_stack_length IS NULL OR final_stack_length > 0)
        )
);


-- 3-phase designs must not have auxiliary winding values.
CREATE OR REPLACE FUNCTION check_winding_matches_phase()
RETURNS TRIGGER AS $$
DECLARE
    design_phase VARCHAR(10);
BEGIN
    SELECT phase INTO design_phase
    FROM designs
    WHERE id = NEW.design_id;

    IF design_phase = '3_phase' AND (
        NEW.insulation_dia_aux IS NOT NULL OR
        NEW.actual_use_dia_aux IS NOT NULL OR
        NEW.final_turns_aux    IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'Auxiliary winding values are only allowed for 1_phase / 2_phase designs (design %)', NEW.design_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- 9. CALCULATIONS
-- One row each time Form 4 is calculated / submitted.
-- Keeps history: a design can be recalculated after edits,
-- and each report points at the exact calculation it shows.
-- ============================================================

CREATE TABLE calculations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    design_id BIGINT NOT NULL,

    -- Currents
    i_ph  NUMERIC(12,4),                 -- 3-phase: phase current (I_ph); 1/2-phase: main current (I_main)
    i_aux NUMERIC(12,4),                 -- 1/2-phase auxiliary current

    -- Recommendations shown on Form 4
    recommended_dia          NUMERIC(10,4),
    recommended_dia_aux      NUMERIC(10,4),
    recommended_turns        NUMERIC(12,3),
    recommended_turns_aux    NUMERIC(12,3),
    recommended_stack_length NUMERIC(12,3),

    -- Performance results
    slip             NUMERIC(10,4),      -- %
    temp             NUMERIC(10,4),      -- °C rise
    statorwt         NUMERIC(12,4),      -- kg
    rotorwt          NUMERIC(12,4),      -- kg
    cu_length        NUMERIC(14,4),      -- copper length
    air_gap          NUMERIC(10,4),      -- mm
    final_efficiency NUMERIC(8,4),       -- %
    angle            NUMERIC(8,4),       -- degrees
    torque           NUMERIC(12,4),      -- Nm

    -- Full copy of all four forms at the moment of calculation,
    -- so an old report can be reproduced even after the design is edited.
    inputs_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT calculations_design_fk
        FOREIGN KEY (design_id)
        REFERENCES designs(id)
        ON DELETE CASCADE,

    CONSTRAINT calculations_snapshot_check
        CHECK (jsonb_typeof(inputs_snapshot) = 'object')
);

CREATE INDEX idx_calculations_design_created
ON calculations(design_id, created_at DESC);


-- ============================================================
-- 10. REPORTS
-- ============================================================

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    design_id BIGINT NOT NULL,

    calculation_id BIGINT NOT NULL,

    report_name VARCHAR(200) NOT NULL,

    file_url TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT reports_design_fk
        FOREIGN KEY (design_id)
        REFERENCES designs(id)
        ON DELETE CASCADE,

    CONSTRAINT reports_calculation_fk
        FOREIGN KEY (calculation_id)
        REFERENCES calculations(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_reports_design_id
ON reports(design_id);

CREATE INDEX idx_reports_calculation_id
ON reports(calculation_id);


-- ============================================================
-- FORM TABLE TRIGGERS
-- ============================================================

-- updated_at on each form table
CREATE TRIGGER update_main_data_updated_at
BEFORE UPDATE ON design_main_data
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_stamping_data_updated_at
BEFORE UPDATE ON design_stamping_data
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_rotor_data_updated_at
BEFORE UPDATE ON design_rotor_data
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_winding_data_updated_at
BEFORE UPDATE ON design_winding_data
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- aux winding only for 1 / 2-phase
CREATE TRIGGER check_winding_phase
BEFORE INSERT OR UPDATE ON design_winding_data
FOR EACH ROW EXECUTE FUNCTION check_winding_matches_phase();

-- saving any form bumps designs.updated_at
CREATE TRIGGER touch_design_from_main
AFTER INSERT OR UPDATE ON design_main_data
FOR EACH ROW EXECUTE FUNCTION touch_parent_design();

CREATE TRIGGER touch_design_from_stamping
AFTER INSERT OR UPDATE ON design_stamping_data
FOR EACH ROW EXECUTE FUNCTION touch_parent_design();

CREATE TRIGGER touch_design_from_rotor
AFTER INSERT OR UPDATE ON design_rotor_data
FOR EACH ROW EXECUTE FUNCTION touch_parent_design();

CREATE TRIGGER touch_design_from_winding
AFTER INSERT OR UPDATE ON design_winding_data
FOR EACH ROW EXECUTE FUNCTION touch_parent_design();

CREATE TRIGGER touch_design_from_calculation
AFTER INSERT ON calculations
FOR EACH ROW EXECUTE FUNCTION touch_parent_design();


-- ============================================================
-- CONVENIENCE VIEW: one row per design with all four forms
-- (handy for the "My Designs" page and for building reports)
-- ============================================================

CREATE VIEW design_full AS
SELECT
    d.id, d.user_id, d.design_no, d.design_name, d.design_date,
    d.phase, d.wire_type, d.mechanical_component,
    d.status, d.current_step, d.created_at, d.updated_at,

    m.connection, m.voltage, m.power, m.hp, m.frequency, m.rpm, m.pole, m.uph, m.capacitor,

    s.material, s.stamping_material, s.n, s.y, s.w, s.w2, s.a1, s.shape,
    s.a, s.b, s.c, s.d, s.e, s.dw, s.d0, s.dia, s.lf_y, s.lf_t,

    r.m, r.rng_wt, r.rng_ht, r.x, r.v, r.v2, r.a2,
    r.ra, r.rb, r.rc, r.rd, r.re, r.rw, r.shaft_diameter,

    wd.current_density, wd.efficiency, wd.insulation_dia, wd.actual_use_dia, wd.final_turns,
    wd.insulation_dia_aux, wd.actual_use_dia_aux, wd.final_turns_aux, wd.final_stack_length
FROM designs d
LEFT JOIN design_main_data     m  ON m.design_id  = d.id
LEFT JOIN design_stamping_data s  ON s.design_id  = d.id
LEFT JOIN design_rotor_data    r  ON r.design_id  = d.id
LEFT JOIN design_winding_data  wd ON wd.design_id = d.id;


-- ============================================================
-- INDEXES (users / subscriptions / payments)
-- ============================================================

CREATE INDEX idx_users_role
ON users(role);

CREATE INDEX idx_subscriptions_user_id
ON subscriptions(user_id);

CREATE INDEX idx_subscriptions_status
ON subscriptions(status);

CREATE INDEX idx_subscriptions_end_date
ON subscriptions(end_date);

CREATE INDEX idx_payments_user_id
ON payments(user_id);

CREATE INDEX idx_payments_subscription_id
ON payments(subscription_id);

CREATE INDEX idx_payments_status
ON payments(status);

CREATE INDEX idx_payments_gateway_order_id
ON payments(gateway_order_id);


-- ============================================================
-- updated_at TRIGGERS (users / subscriptions)
-- (function update_updated_at_column() is created in design_tables.sql)
-- ============================================================

CREATE TRIGGER update_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


CREATE TRIGGER update_subscriptions_updated_at
BEFORE UPDATE ON subscriptions
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- ============================================================
-- DONE
-- ============================================================
